Dockerfile

Update Dockerfile to use v0.0.10

---

transformers/events/bite/converter.go
transformers/events/cat_file/chop_lump/converter.go
transformers/events/cat_file/flip/converter.go
transformers/events/cat_file/vow/converter.go
transformers/events/cat_file/vow/converter_test.go
transformers/events/cat_file/vow/initializer/initializer.go
transformers/events/cat_file/vow/repository.go
transformers/integration_tests/cat_file.go
transformers/shared/constants/keys.go
transformers/shared/converter.go
transformers/test_data/bite.go
transformers/test_data/cat_file.go

using VDB InsertionModel for cat_file_vow

VDB-963 cat file vow

---

environments/docker.toml
environments/mcdTransformers.toml
environments/testing.toml

- also order event transformers alphabetically
forgot to add this earlier 😅

Add pot_file_vow to config files

---

transformers/component_tests/queries/test_helpers/test_helpers.go
transformers/component_tests/triggers/vat_init_trigger_test.go
transformers/events/cat_file/chop_lump/converter_test.go
transformers/events/cat_file/flip/converter_test.go
transformers/events/deal/converter_test.go
transformers/events/dent/converter_test.go
transformers/events/flap_kick/converter_test.go
transformers/events/tend/converter_test.go
transformers/events/tick/converter_test.go
transformers/events/vat_fold/converter_test.go
transformers/events/vat_grab/converter_test.go
transformers/events/vat_heal/converter_test.go
transformers/events/vat_init/converter_test.go
transformers/events/vat_move/converter_test.go
transformers/events/vat_slip/converter_test.go
transformers/events/vat_suck/converter_test.go
transformers/events/vow_fess/converter_test.go
transformers/events/vow_file/converter_test.go
transformers/events/vow_flog/converter_test.go
transformers/events/yank/converter_test.go
transformers/shared/fk_utils_test.go
transformers/storage/cat/repository_test.go
transformers/test_data/deal.go
transformers/test_data/tick.go
transformers/test_data/vat_fold.go
transformers/test_data/vat_init.go
transformers/test_data/vat_slip.go
transformers/test_data/yank.go

Went back to clean up a few previous commits based on more recent feedback
- Fix tests where the database was being initialized` BeforeEach` individual test
- Fix tests to use a copy of `test_data/models`

Clean up db init in tests

---

go.mod
go.sum
transformers/integration_tests/plugin_test.go

updating VDB version to v0.0.11 since that release has been cut

Update vdb version to v0.0.11

---

db/migrations/00001_create_nodes_table.sql
db/migrations/00004_create_checked_headers_table.sql
db/migrations/00006_create_queued_storage_diffs_table.sql
db/migrations/00008_create_receipts_table.sql
db/migrations/00010_create_watched_logs_table.sql
db/migrations/20181114200131_create_vat_storage_tables.sql
db/migrations/20181114200132_create_vow_storage_tables.sql
db/migrations/20190214200343_create_jug_storage_tables.sql
db/migrations/20190215160236_create_cat_storage_tables.sql
db/migrations/20190215160237_create_spot_storage_tables.sql
db/migrations/20190709160237_create_flip_storage_tables.sql
db/migrations/20190711084519_create_flap_storage_tables.sql
db/migrations/20190711091453_create_flip_table.sql
db/migrations/20190711091456_create_flop_storage_tables.sql
db/migrations/20190720000000_create_flop_table_and_triggers.sql
db/migrations/20190726141224_create_flap_table_and_triggers.sql
db/migrations/20190809160237_create_cdp_manager_storage_tables.sql
db/migrations/20191217084519_create_pot_storage_tables.sql
db/schema.sql
go.mod
go.sum

- Omit internal tables from public and maker schemas from the API
- Add alternative names for tables that conflict

(VDB-1125) Enable full and lite API vs same DB

---

README.md

A couple of things that I think would be helpful to add:
- how to add a new transformer
- how to use/query the graphiql API

Updating README to explain current usage

---

go.mod
go.sum
transformers/integration_tests/plugin_test.go

companion PR to https://github.com/makerdao/vulcanizedb/pull/32

Update vdb version

---

db/migrations/00003_create_headers_table.sql
db/schema.sql

Just copied over the migration changes from [the vDB PR](https://github.com/makerdao/vulcanizedb/pull/35)

(VDB-1182) Copy over header changes from vDB

---

dockerfiles/README.md

Authored-by: Sam MacPherson <xylom44@gmail.com>

Typo in the Docker command. (#116)

---

db/migrations/00005_create_storage_diffs_table.sql
db/schema.sql

companion PR to https://github.com/makerdao/vulcanizedb/pull/41

Update db migration to include from_backfill column on storage_diff table

---

go.mod
go.sum
transformers/component_tests/cat/configured_transformer_test.go
transformers/component_tests/cdp_manager/configured_transformer_test.go
transformers/component_tests/flap/configured_transformer_test.go
transformers/component_tests/flip/configured_transformer_test.go
transformers/component_tests/flop/configured_transformer_test.go
transformers/component_tests/jug/configured_transformer_test.go
transformers/component_tests/pot/configured_transformer_test.go
transformers/component_tests/spot/configured_transformer_test.go
transformers/component_tests/vat/configured_transformer_test.go
transformers/component_tests/vow/configured_transformer_test.go
transformers/storage/cat/initializer/initializer.go
transformers/storage/cdp_manager/initializer/initializer.go
transformers/storage/flap/initializer/initializer.go
transformers/storage/flip/initializers/flip_initializer_generator.go
transformers/storage/flop/initializer/initializer.go
transformers/storage/jug/initializer/initializer.go
transformers/storage/pot/initializer/initializer.go
transformers/storage/spot/initializer/initializer.go
transformers/storage/vat/initializer/initializer.go
transformers/storage/vow/initializer/initializer.go

companion vdb PR: https://github.com/makerdao/vulcanizedb/pull/38

1189 add addresses to storage initializers

---

db/migrations/00001_create_nodes_table.sql
db/schema.sql
go.mod
go.sum

Companion to https://github.com/makerdao/vulcanizedb/pull/46

(VDB-1164) Copy over migrations from vDB

---

db/migrations/20200305202405_create_get_or_create_header_function.sql
db/schema.sql
go.mod
go.sum

- Compatibility with upstream vdb changes

(VDB-1218) Add function for inserting headers

---

db/migrations/20200406181508_create_create_back_filled_diff_function.sql
db/schema.sql
dockerfiles/README.md
dockerfiles/backfill_storage/Dockerfile
dockerfiles/backfill_storage/startup_script.sh
go.mod
go.sum

Pointed at the corresponding vDB branch but can switch to staging/release once merged/cut

(VDB-1249) Add Dockerfile for backfill_storage

---

.travis/deploy.sh

- Replace vdb-get-storage-value

Update deploy to include vdb-backfill-storage

---

db/migrations/20200413002054_create_vat_hope.sql
db/migrations/20200413132301_create_vat_hope_and_nope.sql
db/schema.sql
environments/docker.toml
environments/mcdTransformers.toml
environments/testing.toml
plugins/transformerExporter.go
transformers/events/vat_auth/hope_initializer/initializer.go
transformers/events/vat_auth/nope_initializer/initializer.go
transformers/events/vat_auth/transformer_test.go
transformers/integration_tests/vat_hope_test.go
transformers/integration_tests/vat_move_test.go
transformers/integration_tests/vat_nope_test.go
transformers/shared/constants/method.go
transformers/shared/constants/signature.go
transformers/shared/constants/signature_test.go
transformers/shared/constants/table.go
transformers/test_data/vat_hope.go
transformers/test_data/vat_nope.go

Shoutout to @Gslaughl for making this super easy with the `vat_auth` transformer 🎉

(VDB-1267) vat hope/nope

---

environments/docker.toml
environments/mcdTransformers.toml
environments/testing.toml

This seems too easy 😅 lmk if I'm missing something

(VDB-1224) Update config to watch auth events from Median contracts

---

db/migrations/20200416093003_create_log_sorted_offer.sql
db/migrations/20200417103104_create_log_unsorted_offer.sql
db/schema.sql
environments/docker.toml
environments/mcdTransformers.toml
environments/testing.toml
plugins/transformerExporter.go
transformers/events/log_sorted_offer/entity.go
transformers/events/log_sorted_offer/initializer/initializer.go
transformers/events/log_sorted_offer/log_sorted_offer_suite_test.go
transformers/events/log_sorted_offer/transformer.go
transformers/events/log_sorted_offer/transformer_test.go
transformers/events/log_unsorted_offer/entity.go
transformers/events/log_unsorted_offer/initializer/initializer.go
transformers/events/log_unsorted_offer/log_unsorted_offer_suite_test.go
transformers/events/log_unsorted_offer/transformer.go
transformers/events/log_unsorted_offer/transformer_test.go
transformers/integration_tests/log_sorted_offer_test.go
transformers/integration_tests/log_unsorted_offer_test.go
transformers/shared/constants/method.go
transformers/shared/constants/signature.go
transformers/shared/constants/signature_test.go
transformers/shared/constants/table.go
transformers/test_data/log_sorted_offer.go
transformers/test_data/log_unsorted_offer.go

2 nearly-identical transformers in 2 separate commits

(VDB-1279) LogSortedOffer + LogUnsortedOffer transformers

---

db/migrations/20200418115938_create_log_bump.sql
db/schema.sql
environments/docker.toml
environments/mcdTransformers.toml
environments/testing.toml
plugins/transformerExporter.go
transformers/events/log_bump/entity.go
transformers/events/log_bump/initializer/initializer.go
transformers/events/log_bump/log_bump_suite_test.go
transformers/events/log_bump/transformer.go
transformers/events/log_bump/transformer_test.go
transformers/integration_tests/log_bump_test.go
transformers/shared/constants/method.go
transformers/shared/constants/signature.go
transformers/shared/constants/signature_test.go
transformers/shared/constants/table.go
transformers/test_data/log_bump.go

Knockoff of the LogMake transformer 😅

(VDB-1285) LogBump event transformer
